/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "main.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	// Begin initialisation
	enableClocks();
	setupGPIOPinsTim2();
	setupTim2Pwm();

	// Set servo angle
	//servoAngle(2, 70.0);

	TIM2->CCR1 = 20000;
	TIM2->CCR2 = 20000;
	TIM2->CCR3 = 20000;
	TIM2->CCR4 = 20000;



	/* Loop forever */
	while(1) {
	}
}
